wandb_version: 1

Epochs:
  desc: null
  value: 250
Batch size:
  desc: null
  value: 32
Device:
  desc: null
  value: cpu
k-fold:
  desc: null
  value: 10
Dataset:
  desc: null
  value: PROTEINS
learning_rate:
  desc: null
  value: 0.02
seed:
  desc: null
  value: 42
k_wl:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684107458.699725
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 1
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 4
      - 5
    m:
    - 1: epoch
      6:
      - 3
    - 1: 'train accuracy: fold 1'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 1'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 1'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 1'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 2'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 2'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 2'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 2'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 3'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 3'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 3'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 3'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 4'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 4'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 4'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 4'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 5'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 5'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 5'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 5'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 6'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 6'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 6'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 6'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 7'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 7'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 7'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 7'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 8'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 8'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 8'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 8'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 9'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 9'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 9'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 9'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'train accuracy: fold 10'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'val accuracy: fold 10'
      5: 1
      6:
      - 1
      7:
      - 2
    - 1: 'train loss: fold 10'
      5: 1
      6:
      - 1
      7:
      - 1
    - 1: 'val loss: fold 10'
      5: 1
      6:
      - 1
      7:
      - 1
